// ==============================================================
// Generated by Vitis HLS v2026.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module w4a8_linear_v1_p_anonymous_namespace_prefill_overlap (
        m_axi_gmem_w_0_AWVALID,
        m_axi_gmem_w_0_AWREADY,
        m_axi_gmem_w_0_AWADDR,
        m_axi_gmem_w_0_AWID,
        m_axi_gmem_w_0_AWLEN,
        m_axi_gmem_w_0_AWSIZE,
        m_axi_gmem_w_0_AWBURST,
        m_axi_gmem_w_0_AWLOCK,
        m_axi_gmem_w_0_AWCACHE,
        m_axi_gmem_w_0_AWPROT,
        m_axi_gmem_w_0_AWQOS,
        m_axi_gmem_w_0_AWREGION,
        m_axi_gmem_w_0_AWUSER,
        m_axi_gmem_w_0_WVALID,
        m_axi_gmem_w_0_WREADY,
        m_axi_gmem_w_0_WDATA,
        m_axi_gmem_w_0_WSTRB,
        m_axi_gmem_w_0_WLAST,
        m_axi_gmem_w_0_WID,
        m_axi_gmem_w_0_WUSER,
        m_axi_gmem_w_0_ARVALID,
        m_axi_gmem_w_0_ARREADY,
        m_axi_gmem_w_0_ARADDR,
        m_axi_gmem_w_0_ARID,
        m_axi_gmem_w_0_ARLEN,
        m_axi_gmem_w_0_ARSIZE,
        m_axi_gmem_w_0_ARBURST,
        m_axi_gmem_w_0_ARLOCK,
        m_axi_gmem_w_0_ARCACHE,
        m_axi_gmem_w_0_ARPROT,
        m_axi_gmem_w_0_ARQOS,
        m_axi_gmem_w_0_ARREGION,
        m_axi_gmem_w_0_ARUSER,
        m_axi_gmem_w_0_RVALID,
        m_axi_gmem_w_0_RREADY,
        m_axi_gmem_w_0_RDATA,
        m_axi_gmem_w_0_RLAST,
        m_axi_gmem_w_0_RID,
        m_axi_gmem_w_0_RFIFONUM,
        m_axi_gmem_w_0_RUSER,
        m_axi_gmem_w_0_RRESP,
        m_axi_gmem_w_0_BVALID,
        m_axi_gmem_w_0_BREADY,
        m_axi_gmem_w_0_BRESP,
        m_axi_gmem_w_0_BID,
        m_axi_gmem_w_0_BUSER,
        w_packed,
        m_axi_gmem_sw_0_AWVALID,
        m_axi_gmem_sw_0_AWREADY,
        m_axi_gmem_sw_0_AWADDR,
        m_axi_gmem_sw_0_AWID,
        m_axi_gmem_sw_0_AWLEN,
        m_axi_gmem_sw_0_AWSIZE,
        m_axi_gmem_sw_0_AWBURST,
        m_axi_gmem_sw_0_AWLOCK,
        m_axi_gmem_sw_0_AWCACHE,
        m_axi_gmem_sw_0_AWPROT,
        m_axi_gmem_sw_0_AWQOS,
        m_axi_gmem_sw_0_AWREGION,
        m_axi_gmem_sw_0_AWUSER,
        m_axi_gmem_sw_0_WVALID,
        m_axi_gmem_sw_0_WREADY,
        m_axi_gmem_sw_0_WDATA,
        m_axi_gmem_sw_0_WSTRB,
        m_axi_gmem_sw_0_WLAST,
        m_axi_gmem_sw_0_WID,
        m_axi_gmem_sw_0_WUSER,
        m_axi_gmem_sw_0_ARVALID,
        m_axi_gmem_sw_0_ARREADY,
        m_axi_gmem_sw_0_ARADDR,
        m_axi_gmem_sw_0_ARID,
        m_axi_gmem_sw_0_ARLEN,
        m_axi_gmem_sw_0_ARSIZE,
        m_axi_gmem_sw_0_ARBURST,
        m_axi_gmem_sw_0_ARLOCK,
        m_axi_gmem_sw_0_ARCACHE,
        m_axi_gmem_sw_0_ARPROT,
        m_axi_gmem_sw_0_ARQOS,
        m_axi_gmem_sw_0_ARREGION,
        m_axi_gmem_sw_0_ARUSER,
        m_axi_gmem_sw_0_RVALID,
        m_axi_gmem_sw_0_RREADY,
        m_axi_gmem_sw_0_RDATA,
        m_axi_gmem_sw_0_RLAST,
        m_axi_gmem_sw_0_RID,
        m_axi_gmem_sw_0_RFIFONUM,
        m_axi_gmem_sw_0_RUSER,
        m_axi_gmem_sw_0_RRESP,
        m_axi_gmem_sw_0_BVALID,
        m_axi_gmem_sw_0_BREADY,
        m_axi_gmem_sw_0_BRESP,
        m_axi_gmem_sw_0_BID,
        m_axi_gmem_sw_0_BUSER,
        sw,
        next_tile_group,
        has_next,
        next_weights_address0,
        next_weights_ce0,
        next_weights_d0,
        next_weights_q0,
        next_weights_we0,
        next_weights_address1,
        next_weights_ce1,
        next_weights_d1,
        next_weights_q1,
        next_weights_we1,
        next_scales_address0,
        next_scales_ce0,
        next_scales_d0,
        next_scales_q0,
        next_scales_we0,
        next_scales_address1,
        next_scales_ce1,
        next_scales_d1,
        next_scales_q1,
        next_scales_we1,
        current_weights_address0,
        current_weights_ce0,
        current_weights_d0,
        current_weights_q0,
        current_weights_we0,
        current_weights_address1,
        current_weights_ce1,
        current_weights_d1,
        current_weights_q1,
        current_weights_we1,
        current_scales_address0,
        current_scales_ce0,
        current_scales_d0,
        current_scales_q0,
        current_scales_we0,
        current_scales_address1,
        current_scales_ce1,
        current_scales_d1,
        current_scales_q1,
        current_scales_we1,
        activations_address0,
        activations_ce0,
        activations_d0,
        activations_q0,
        activations_we0,
        token_scales_address0,
        token_scales_ce0,
        token_scales_d0,
        token_scales_q0,
        token_scales_we0,
        token_scales_address1,
        token_scales_ce1,
        token_scales_d1,
        token_scales_q1,
        token_scales_we1,
        totals_address0,
        totals_ce0,
        totals_d0,
        totals_q0,
        totals_we0,
        totals_address1,
        totals_ce1,
        totals_d1,
        totals_q1,
        totals_we1,
        t,
        group_r,
        ap_clk,
        ap_rst,
        w_packed_ap_vld,
        sw_ap_vld,
        next_tile_group_ap_vld,
        has_next_ap_vld,
        ap_start,
        ap_done,
        t_ap_vld,
        group_r_ap_vld,
        ap_ready,
        ap_idle,
        ap_continue
);


output   m_axi_gmem_w_0_AWVALID;
input   m_axi_gmem_w_0_AWREADY;
output  [63:0] m_axi_gmem_w_0_AWADDR;
output  [0:0] m_axi_gmem_w_0_AWID;
output  [31:0] m_axi_gmem_w_0_AWLEN;
output  [2:0] m_axi_gmem_w_0_AWSIZE;
output  [1:0] m_axi_gmem_w_0_AWBURST;
output  [1:0] m_axi_gmem_w_0_AWLOCK;
output  [3:0] m_axi_gmem_w_0_AWCACHE;
output  [2:0] m_axi_gmem_w_0_AWPROT;
output  [3:0] m_axi_gmem_w_0_AWQOS;
output  [3:0] m_axi_gmem_w_0_AWREGION;
output  [0:0] m_axi_gmem_w_0_AWUSER;
output   m_axi_gmem_w_0_WVALID;
input   m_axi_gmem_w_0_WREADY;
output  [127:0] m_axi_gmem_w_0_WDATA;
output  [15:0] m_axi_gmem_w_0_WSTRB;
output   m_axi_gmem_w_0_WLAST;
output  [0:0] m_axi_gmem_w_0_WID;
output  [0:0] m_axi_gmem_w_0_WUSER;
output   m_axi_gmem_w_0_ARVALID;
input   m_axi_gmem_w_0_ARREADY;
output  [63:0] m_axi_gmem_w_0_ARADDR;
output  [0:0] m_axi_gmem_w_0_ARID;
output  [31:0] m_axi_gmem_w_0_ARLEN;
output  [2:0] m_axi_gmem_w_0_ARSIZE;
output  [1:0] m_axi_gmem_w_0_ARBURST;
output  [1:0] m_axi_gmem_w_0_ARLOCK;
output  [3:0] m_axi_gmem_w_0_ARCACHE;
output  [2:0] m_axi_gmem_w_0_ARPROT;
output  [3:0] m_axi_gmem_w_0_ARQOS;
output  [3:0] m_axi_gmem_w_0_ARREGION;
output  [0:0] m_axi_gmem_w_0_ARUSER;
input   m_axi_gmem_w_0_RVALID;
output   m_axi_gmem_w_0_RREADY;
input  [127:0] m_axi_gmem_w_0_RDATA;
input   m_axi_gmem_w_0_RLAST;
input  [0:0] m_axi_gmem_w_0_RID;
input  [11:0] m_axi_gmem_w_0_RFIFONUM;
input  [0:0] m_axi_gmem_w_0_RUSER;
input  [1:0] m_axi_gmem_w_0_RRESP;
input   m_axi_gmem_w_0_BVALID;
output   m_axi_gmem_w_0_BREADY;
input  [1:0] m_axi_gmem_w_0_BRESP;
input  [0:0] m_axi_gmem_w_0_BID;
input  [0:0] m_axi_gmem_w_0_BUSER;
input  [63:0] w_packed;
output   m_axi_gmem_sw_0_AWVALID;
input   m_axi_gmem_sw_0_AWREADY;
output  [63:0] m_axi_gmem_sw_0_AWADDR;
output  [0:0] m_axi_gmem_sw_0_AWID;
output  [31:0] m_axi_gmem_sw_0_AWLEN;
output  [2:0] m_axi_gmem_sw_0_AWSIZE;
output  [1:0] m_axi_gmem_sw_0_AWBURST;
output  [1:0] m_axi_gmem_sw_0_AWLOCK;
output  [3:0] m_axi_gmem_sw_0_AWCACHE;
output  [2:0] m_axi_gmem_sw_0_AWPROT;
output  [3:0] m_axi_gmem_sw_0_AWQOS;
output  [3:0] m_axi_gmem_sw_0_AWREGION;
output  [0:0] m_axi_gmem_sw_0_AWUSER;
output   m_axi_gmem_sw_0_WVALID;
input   m_axi_gmem_sw_0_WREADY;
output  [31:0] m_axi_gmem_sw_0_WDATA;
output  [3:0] m_axi_gmem_sw_0_WSTRB;
output   m_axi_gmem_sw_0_WLAST;
output  [0:0] m_axi_gmem_sw_0_WID;
output  [0:0] m_axi_gmem_sw_0_WUSER;
output   m_axi_gmem_sw_0_ARVALID;
input   m_axi_gmem_sw_0_ARREADY;
output  [63:0] m_axi_gmem_sw_0_ARADDR;
output  [0:0] m_axi_gmem_sw_0_ARID;
output  [31:0] m_axi_gmem_sw_0_ARLEN;
output  [2:0] m_axi_gmem_sw_0_ARSIZE;
output  [1:0] m_axi_gmem_sw_0_ARBURST;
output  [1:0] m_axi_gmem_sw_0_ARLOCK;
output  [3:0] m_axi_gmem_sw_0_ARCACHE;
output  [2:0] m_axi_gmem_sw_0_ARPROT;
output  [3:0] m_axi_gmem_sw_0_ARQOS;
output  [3:0] m_axi_gmem_sw_0_ARREGION;
output  [0:0] m_axi_gmem_sw_0_ARUSER;
input   m_axi_gmem_sw_0_RVALID;
output   m_axi_gmem_sw_0_RREADY;
input  [31:0] m_axi_gmem_sw_0_RDATA;
input   m_axi_gmem_sw_0_RLAST;
input  [0:0] m_axi_gmem_sw_0_RID;
input  [9:0] m_axi_gmem_sw_0_RFIFONUM;
input  [0:0] m_axi_gmem_sw_0_RUSER;
input  [1:0] m_axi_gmem_sw_0_RRESP;
input   m_axi_gmem_sw_0_BVALID;
output   m_axi_gmem_sw_0_BREADY;
input  [1:0] m_axi_gmem_sw_0_BRESP;
input  [0:0] m_axi_gmem_sw_0_BID;
input  [0:0] m_axi_gmem_sw_0_BUSER;
input  [63:0] sw;
input  [51:0] next_tile_group;
input  [0:0] has_next;
output  [6:0] next_weights_address0;
output   next_weights_ce0;
output  [127:0] next_weights_d0;
input  [127:0] next_weights_q0;
output   next_weights_we0;
output  [6:0] next_weights_address1;
output   next_weights_ce1;
output  [127:0] next_weights_d1;
input  [127:0] next_weights_q1;
output   next_weights_we1;
output  [4:0] next_scales_address0;
output   next_scales_ce0;
output  [31:0] next_scales_d0;
input  [31:0] next_scales_q0;
output   next_scales_we0;
output  [4:0] next_scales_address1;
output   next_scales_ce1;
output  [31:0] next_scales_d1;
input  [31:0] next_scales_q1;
output   next_scales_we1;
output  [6:0] current_weights_address0;
output   current_weights_ce0;
output  [127:0] current_weights_d0;
input  [127:0] current_weights_q0;
output   current_weights_we0;
output  [6:0] current_weights_address1;
output   current_weights_ce1;
output  [127:0] current_weights_d1;
input  [127:0] current_weights_q1;
output   current_weights_we1;
output  [4:0] current_scales_address0;
output   current_scales_ce0;
output  [31:0] current_scales_d0;
input  [31:0] current_scales_q0;
output   current_scales_we0;
output  [4:0] current_scales_address1;
output   current_scales_ce1;
output  [31:0] current_scales_d1;
input  [31:0] current_scales_q1;
output   current_scales_we1;
output  [15:0] activations_address0;
output   activations_ce0;
output  [7:0] activations_d0;
input  [7:0] activations_q0;
output   activations_we0;
output  [2:0] token_scales_address0;
output   token_scales_ce0;
output  [31:0] token_scales_d0;
input  [31:0] token_scales_q0;
output   token_scales_we0;
output  [2:0] token_scales_address1;
output   token_scales_ce1;
output  [31:0] token_scales_d1;
input  [31:0] token_scales_q1;
output   token_scales_we1;
output  [7:0] totals_address0;
output   totals_ce0;
output  [31:0] totals_d0;
input  [31:0] totals_q0;
output   totals_we0;
output  [7:0] totals_address1;
output   totals_ce1;
output  [31:0] totals_d1;
input  [31:0] totals_q1;
output   totals_we1;
input  [31:0] t;
input  [24:0] group_r;
input   ap_clk;
input   ap_rst;
input   w_packed_ap_vld;
input   sw_ap_vld;
input   next_tile_group_ap_vld;
input   has_next_ap_vld;
input   ap_start;
output   ap_done;
input   t_ap_vld;
input   group_r_ap_vld;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    p_anonymous_namespace_load_prefill_group_1_U0_ap_start;
wire    p_anonymous_namespace_load_prefill_group_1_U0_ap_done;
wire    p_anonymous_namespace_load_prefill_group_1_U0_ap_continue;
wire    p_anonymous_namespace_load_prefill_group_1_U0_ap_idle;
wire    p_anonymous_namespace_load_prefill_group_1_U0_ap_ready;
wire    p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWVALID;
wire   [63:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWADDR;
wire   [0:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWID;
wire   [31:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWLEN;
wire   [2:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWSIZE;
wire   [1:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWBURST;
wire   [1:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWLOCK;
wire   [3:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWCACHE;
wire   [2:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWPROT;
wire   [3:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWQOS;
wire   [3:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWREGION;
wire   [0:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWUSER;
wire    p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_WVALID;
wire   [127:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_WDATA;
wire   [15:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_WSTRB;
wire    p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_WLAST;
wire   [0:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_WID;
wire   [0:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_WUSER;
wire    p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARVALID;
wire   [63:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARADDR;
wire   [0:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARID;
wire   [31:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARLEN;
wire   [2:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARSIZE;
wire   [1:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARBURST;
wire   [1:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARLOCK;
wire   [3:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARCACHE;
wire   [2:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARPROT;
wire   [3:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARQOS;
wire   [3:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARREGION;
wire   [0:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARUSER;
wire    p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_RREADY;
wire    p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_BREADY;
wire    p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWVALID;
wire   [63:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWADDR;
wire   [0:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWID;
wire   [31:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWLEN;
wire   [2:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWSIZE;
wire   [1:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWBURST;
wire   [1:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWLOCK;
wire   [3:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWCACHE;
wire   [2:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWPROT;
wire   [3:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWQOS;
wire   [3:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWREGION;
wire   [0:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWUSER;
wire    p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_WVALID;
wire   [31:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_WDATA;
wire   [3:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_WSTRB;
wire    p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_WLAST;
wire   [0:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_WID;
wire   [0:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_WUSER;
wire    p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARVALID;
wire   [63:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARADDR;
wire   [0:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARID;
wire   [31:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARLEN;
wire   [2:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARSIZE;
wire   [1:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARBURST;
wire   [1:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARLOCK;
wire   [3:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARCACHE;
wire   [2:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARPROT;
wire   [3:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARQOS;
wire   [3:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARREGION;
wire   [0:0] p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARUSER;
wire    p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_RREADY;
wire    p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_BREADY;
wire   [6:0] p_anonymous_namespace_load_prefill_group_1_U0_weights_address0;
wire    p_anonymous_namespace_load_prefill_group_1_U0_weights_ce0;
wire    p_anonymous_namespace_load_prefill_group_1_U0_weights_we0;
wire   [127:0] p_anonymous_namespace_load_prefill_group_1_U0_weights_d0;
wire   [4:0] p_anonymous_namespace_load_prefill_group_1_U0_scales_address0;
wire    p_anonymous_namespace_load_prefill_group_1_U0_scales_ce0;
wire    p_anonymous_namespace_load_prefill_group_1_U0_scales_we0;
wire   [31:0] p_anonymous_namespace_load_prefill_group_1_U0_scales_d0;
wire    ap_sync_continue;
wire    p_anonymous_namespace_compute_prefill_group_U0_ap_start;
wire    p_anonymous_namespace_compute_prefill_group_U0_ap_done;
wire    p_anonymous_namespace_compute_prefill_group_U0_ap_continue;
wire    p_anonymous_namespace_compute_prefill_group_U0_ap_idle;
wire    p_anonymous_namespace_compute_prefill_group_U0_ap_ready;
wire   [6:0] p_anonymous_namespace_compute_prefill_group_U0_weights_address0;
wire    p_anonymous_namespace_compute_prefill_group_U0_weights_ce0;
wire   [4:0] p_anonymous_namespace_compute_prefill_group_U0_scales_address0;
wire    p_anonymous_namespace_compute_prefill_group_U0_scales_ce0;
wire   [15:0] p_anonymous_namespace_compute_prefill_group_U0_activations_address0;
wire    p_anonymous_namespace_compute_prefill_group_U0_activations_ce0;
wire   [2:0] p_anonymous_namespace_compute_prefill_group_U0_token_scales_address0;
wire    p_anonymous_namespace_compute_prefill_group_U0_token_scales_ce0;
wire   [7:0] p_anonymous_namespace_compute_prefill_group_U0_totals_address0;
wire    p_anonymous_namespace_compute_prefill_group_U0_totals_ce0;
wire    p_anonymous_namespace_compute_prefill_group_U0_totals_we0;
wire   [31:0] p_anonymous_namespace_compute_prefill_group_U0_totals_d0;
wire   [7:0] p_anonymous_namespace_compute_prefill_group_U0_totals_address1;
wire    p_anonymous_namespace_compute_prefill_group_U0_totals_ce1;
reg    ap_sync_done;
reg    ap_sync_ready;
reg    ap_sync_reg_p_anonymous_namespace_load_prefill_group_1_U0_ap_ready;
wire    ap_sync_p_anonymous_namespace_load_prefill_group_1_U0_ap_ready;
reg    ap_sync_reg_p_anonymous_namespace_compute_prefill_group_U0_ap_ready;
wire    ap_sync_p_anonymous_namespace_compute_prefill_group_U0_ap_ready;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_p_anonymous_namespace_load_prefill_group_1_U0_ap_ready = 1'b0;
#0 ap_sync_reg_p_anonymous_namespace_compute_prefill_group_U0_ap_ready = 1'b0;
end

w4a8_linear_v1_p_anonymous_namespace_load_prefill_group_1 p_anonymous_namespace_load_prefill_group_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(p_anonymous_namespace_load_prefill_group_1_U0_ap_start),
    .ap_done(p_anonymous_namespace_load_prefill_group_1_U0_ap_done),
    .ap_continue(p_anonymous_namespace_load_prefill_group_1_U0_ap_continue),
    .ap_idle(p_anonymous_namespace_load_prefill_group_1_U0_ap_idle),
    .ap_ready(p_anonymous_namespace_load_prefill_group_1_U0_ap_ready),
    .m_axi_gmem_w_0_AWVALID(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWVALID),
    .m_axi_gmem_w_0_AWREADY(1'b0),
    .m_axi_gmem_w_0_AWADDR(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWADDR),
    .m_axi_gmem_w_0_AWID(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWID),
    .m_axi_gmem_w_0_AWLEN(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWLEN),
    .m_axi_gmem_w_0_AWSIZE(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWSIZE),
    .m_axi_gmem_w_0_AWBURST(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWBURST),
    .m_axi_gmem_w_0_AWLOCK(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWLOCK),
    .m_axi_gmem_w_0_AWCACHE(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWCACHE),
    .m_axi_gmem_w_0_AWPROT(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWPROT),
    .m_axi_gmem_w_0_AWQOS(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWQOS),
    .m_axi_gmem_w_0_AWREGION(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWREGION),
    .m_axi_gmem_w_0_AWUSER(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_AWUSER),
    .m_axi_gmem_w_0_WVALID(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_WVALID),
    .m_axi_gmem_w_0_WREADY(1'b0),
    .m_axi_gmem_w_0_WDATA(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_WDATA),
    .m_axi_gmem_w_0_WSTRB(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_WSTRB),
    .m_axi_gmem_w_0_WLAST(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_WLAST),
    .m_axi_gmem_w_0_WID(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_WID),
    .m_axi_gmem_w_0_WUSER(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_WUSER),
    .m_axi_gmem_w_0_ARVALID(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARVALID),
    .m_axi_gmem_w_0_ARREADY(m_axi_gmem_w_0_ARREADY),
    .m_axi_gmem_w_0_ARADDR(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARADDR),
    .m_axi_gmem_w_0_ARID(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARID),
    .m_axi_gmem_w_0_ARLEN(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARLEN),
    .m_axi_gmem_w_0_ARSIZE(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARSIZE),
    .m_axi_gmem_w_0_ARBURST(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARBURST),
    .m_axi_gmem_w_0_ARLOCK(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARLOCK),
    .m_axi_gmem_w_0_ARCACHE(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARCACHE),
    .m_axi_gmem_w_0_ARPROT(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARPROT),
    .m_axi_gmem_w_0_ARQOS(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARQOS),
    .m_axi_gmem_w_0_ARREGION(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARREGION),
    .m_axi_gmem_w_0_ARUSER(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARUSER),
    .m_axi_gmem_w_0_RVALID(m_axi_gmem_w_0_RVALID),
    .m_axi_gmem_w_0_RREADY(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_RREADY),
    .m_axi_gmem_w_0_RDATA(m_axi_gmem_w_0_RDATA),
    .m_axi_gmem_w_0_RLAST(m_axi_gmem_w_0_RLAST),
    .m_axi_gmem_w_0_RID(m_axi_gmem_w_0_RID),
    .m_axi_gmem_w_0_RFIFONUM(m_axi_gmem_w_0_RFIFONUM),
    .m_axi_gmem_w_0_RUSER(m_axi_gmem_w_0_RUSER),
    .m_axi_gmem_w_0_RRESP(m_axi_gmem_w_0_RRESP),
    .m_axi_gmem_w_0_BVALID(1'b0),
    .m_axi_gmem_w_0_BREADY(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_BREADY),
    .m_axi_gmem_w_0_BRESP(2'd0),
    .m_axi_gmem_w_0_BID(1'd0),
    .m_axi_gmem_w_0_BUSER(1'd0),
    .w_packed(w_packed),
    .m_axi_gmem_sw_0_AWVALID(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWVALID),
    .m_axi_gmem_sw_0_AWREADY(1'b0),
    .m_axi_gmem_sw_0_AWADDR(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWADDR),
    .m_axi_gmem_sw_0_AWID(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWID),
    .m_axi_gmem_sw_0_AWLEN(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWLEN),
    .m_axi_gmem_sw_0_AWSIZE(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWSIZE),
    .m_axi_gmem_sw_0_AWBURST(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWBURST),
    .m_axi_gmem_sw_0_AWLOCK(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWLOCK),
    .m_axi_gmem_sw_0_AWCACHE(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWCACHE),
    .m_axi_gmem_sw_0_AWPROT(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWPROT),
    .m_axi_gmem_sw_0_AWQOS(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWQOS),
    .m_axi_gmem_sw_0_AWREGION(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWREGION),
    .m_axi_gmem_sw_0_AWUSER(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_AWUSER),
    .m_axi_gmem_sw_0_WVALID(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_WVALID),
    .m_axi_gmem_sw_0_WREADY(1'b0),
    .m_axi_gmem_sw_0_WDATA(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_WDATA),
    .m_axi_gmem_sw_0_WSTRB(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_WSTRB),
    .m_axi_gmem_sw_0_WLAST(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_WLAST),
    .m_axi_gmem_sw_0_WID(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_WID),
    .m_axi_gmem_sw_0_WUSER(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_WUSER),
    .m_axi_gmem_sw_0_ARVALID(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARVALID),
    .m_axi_gmem_sw_0_ARREADY(m_axi_gmem_sw_0_ARREADY),
    .m_axi_gmem_sw_0_ARADDR(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARADDR),
    .m_axi_gmem_sw_0_ARID(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARID),
    .m_axi_gmem_sw_0_ARLEN(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARLEN),
    .m_axi_gmem_sw_0_ARSIZE(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARSIZE),
    .m_axi_gmem_sw_0_ARBURST(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARBURST),
    .m_axi_gmem_sw_0_ARLOCK(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARLOCK),
    .m_axi_gmem_sw_0_ARCACHE(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARCACHE),
    .m_axi_gmem_sw_0_ARPROT(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARPROT),
    .m_axi_gmem_sw_0_ARQOS(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARQOS),
    .m_axi_gmem_sw_0_ARREGION(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARREGION),
    .m_axi_gmem_sw_0_ARUSER(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARUSER),
    .m_axi_gmem_sw_0_RVALID(m_axi_gmem_sw_0_RVALID),
    .m_axi_gmem_sw_0_RREADY(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_RREADY),
    .m_axi_gmem_sw_0_RDATA(m_axi_gmem_sw_0_RDATA),
    .m_axi_gmem_sw_0_RLAST(m_axi_gmem_sw_0_RLAST),
    .m_axi_gmem_sw_0_RID(m_axi_gmem_sw_0_RID),
    .m_axi_gmem_sw_0_RFIFONUM(m_axi_gmem_sw_0_RFIFONUM),
    .m_axi_gmem_sw_0_RUSER(m_axi_gmem_sw_0_RUSER),
    .m_axi_gmem_sw_0_RRESP(m_axi_gmem_sw_0_RRESP),
    .m_axi_gmem_sw_0_BVALID(1'b0),
    .m_axi_gmem_sw_0_BREADY(p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_BREADY),
    .m_axi_gmem_sw_0_BRESP(2'd0),
    .m_axi_gmem_sw_0_BID(1'd0),
    .m_axi_gmem_sw_0_BUSER(1'd0),
    .sw(sw),
    .tile_group(next_tile_group),
    .enabled(has_next),
    .weights_address0(p_anonymous_namespace_load_prefill_group_1_U0_weights_address0),
    .weights_ce0(p_anonymous_namespace_load_prefill_group_1_U0_weights_ce0),
    .weights_we0(p_anonymous_namespace_load_prefill_group_1_U0_weights_we0),
    .weights_d0(p_anonymous_namespace_load_prefill_group_1_U0_weights_d0),
    .scales_address0(p_anonymous_namespace_load_prefill_group_1_U0_scales_address0),
    .scales_ce0(p_anonymous_namespace_load_prefill_group_1_U0_scales_ce0),
    .scales_we0(p_anonymous_namespace_load_prefill_group_1_U0_scales_we0),
    .scales_d0(p_anonymous_namespace_load_prefill_group_1_U0_scales_d0)
);

w4a8_linear_v1_p_anonymous_namespace_compute_prefill_group p_anonymous_namespace_compute_prefill_group_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(p_anonymous_namespace_compute_prefill_group_U0_ap_start),
    .ap_done(p_anonymous_namespace_compute_prefill_group_U0_ap_done),
    .ap_continue(p_anonymous_namespace_compute_prefill_group_U0_ap_continue),
    .ap_idle(p_anonymous_namespace_compute_prefill_group_U0_ap_idle),
    .ap_ready(p_anonymous_namespace_compute_prefill_group_U0_ap_ready),
    .weights_address0(p_anonymous_namespace_compute_prefill_group_U0_weights_address0),
    .weights_ce0(p_anonymous_namespace_compute_prefill_group_U0_weights_ce0),
    .weights_q0(current_weights_q0),
    .scales_address0(p_anonymous_namespace_compute_prefill_group_U0_scales_address0),
    .scales_ce0(p_anonymous_namespace_compute_prefill_group_U0_scales_ce0),
    .scales_q0(current_scales_q0),
    .activations_address0(p_anonymous_namespace_compute_prefill_group_U0_activations_address0),
    .activations_ce0(p_anonymous_namespace_compute_prefill_group_U0_activations_ce0),
    .activations_q0(activations_q0),
    .token_scales_address0(p_anonymous_namespace_compute_prefill_group_U0_token_scales_address0),
    .token_scales_ce0(p_anonymous_namespace_compute_prefill_group_U0_token_scales_ce0),
    .token_scales_q0(token_scales_q0),
    .totals_address0(p_anonymous_namespace_compute_prefill_group_U0_totals_address0),
    .totals_ce0(p_anonymous_namespace_compute_prefill_group_U0_totals_ce0),
    .totals_we0(p_anonymous_namespace_compute_prefill_group_U0_totals_we0),
    .totals_d0(p_anonymous_namespace_compute_prefill_group_U0_totals_d0),
    .totals_address1(p_anonymous_namespace_compute_prefill_group_U0_totals_address1),
    .totals_ce1(p_anonymous_namespace_compute_prefill_group_U0_totals_ce1),
    .totals_q1(totals_q1),
    .t(t),
    .group_r(group_r)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_p_anonymous_namespace_compute_prefill_group_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_p_anonymous_namespace_compute_prefill_group_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_p_anonymous_namespace_compute_prefill_group_U0_ap_ready <= ap_sync_p_anonymous_namespace_compute_prefill_group_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_p_anonymous_namespace_load_prefill_group_1_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_p_anonymous_namespace_load_prefill_group_1_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_p_anonymous_namespace_load_prefill_group_1_U0_ap_ready <= ap_sync_p_anonymous_namespace_load_prefill_group_1_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_sync_done <= (p_anonymous_namespace_load_prefill_group_1_U0_ap_done & p_anonymous_namespace_compute_prefill_group_U0_ap_done & ~ap_sync_continue);
end

always @ (posedge ap_clk) begin
    ap_sync_ready <= (~ap_sync_ready & ap_sync_p_anonymous_namespace_load_prefill_group_1_U0_ap_ready & ap_sync_p_anonymous_namespace_compute_prefill_group_U0_ap_ready & ap_start);
end

assign activations_address0 = p_anonymous_namespace_compute_prefill_group_U0_activations_address0;

assign activations_ce0 = p_anonymous_namespace_compute_prefill_group_U0_activations_ce0;

assign activations_d0 = 8'd0;

assign activations_we0 = 1'b0;

assign ap_done = ap_sync_done;

assign ap_idle = (p_anonymous_namespace_load_prefill_group_1_U0_ap_idle & p_anonymous_namespace_compute_prefill_group_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_continue = (ap_sync_done & ap_continue);

assign ap_sync_p_anonymous_namespace_compute_prefill_group_U0_ap_ready = (p_anonymous_namespace_compute_prefill_group_U0_ap_ready | ap_sync_reg_p_anonymous_namespace_compute_prefill_group_U0_ap_ready);

assign ap_sync_p_anonymous_namespace_load_prefill_group_1_U0_ap_ready = (p_anonymous_namespace_load_prefill_group_1_U0_ap_ready | ap_sync_reg_p_anonymous_namespace_load_prefill_group_1_U0_ap_ready);

assign current_scales_address0 = p_anonymous_namespace_compute_prefill_group_U0_scales_address0;

assign current_scales_address1 = 5'd0;

assign current_scales_ce0 = p_anonymous_namespace_compute_prefill_group_U0_scales_ce0;

assign current_scales_ce1 = 1'b0;

assign current_scales_d0 = 32'd0;

assign current_scales_d1 = 32'd0;

assign current_scales_we0 = 1'b0;

assign current_scales_we1 = 1'b0;

assign current_weights_address0 = p_anonymous_namespace_compute_prefill_group_U0_weights_address0;

assign current_weights_address1 = 7'd0;

assign current_weights_ce0 = p_anonymous_namespace_compute_prefill_group_U0_weights_ce0;

assign current_weights_ce1 = 1'b0;

assign current_weights_d0 = 128'd0;

assign current_weights_d1 = 128'd0;

assign current_weights_we0 = 1'b0;

assign current_weights_we1 = 1'b0;

assign m_axi_gmem_sw_0_ARADDR = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARADDR;

assign m_axi_gmem_sw_0_ARBURST = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARBURST;

assign m_axi_gmem_sw_0_ARCACHE = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARCACHE;

assign m_axi_gmem_sw_0_ARID = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARID;

assign m_axi_gmem_sw_0_ARLEN = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARLEN;

assign m_axi_gmem_sw_0_ARLOCK = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARLOCK;

assign m_axi_gmem_sw_0_ARPROT = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARPROT;

assign m_axi_gmem_sw_0_ARQOS = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARQOS;

assign m_axi_gmem_sw_0_ARREGION = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARREGION;

assign m_axi_gmem_sw_0_ARSIZE = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARSIZE;

assign m_axi_gmem_sw_0_ARUSER = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARUSER;

assign m_axi_gmem_sw_0_ARVALID = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_ARVALID;

assign m_axi_gmem_sw_0_AWADDR = 64'd0;

assign m_axi_gmem_sw_0_AWBURST = 2'd0;

assign m_axi_gmem_sw_0_AWCACHE = 4'd0;

assign m_axi_gmem_sw_0_AWID = 1'd0;

assign m_axi_gmem_sw_0_AWLEN = 32'd0;

assign m_axi_gmem_sw_0_AWLOCK = 2'd0;

assign m_axi_gmem_sw_0_AWPROT = 3'd0;

assign m_axi_gmem_sw_0_AWQOS = 4'd0;

assign m_axi_gmem_sw_0_AWREGION = 4'd0;

assign m_axi_gmem_sw_0_AWSIZE = 3'd0;

assign m_axi_gmem_sw_0_AWUSER = 1'd0;

assign m_axi_gmem_sw_0_AWVALID = 1'b0;

assign m_axi_gmem_sw_0_BREADY = 1'b0;

assign m_axi_gmem_sw_0_RREADY = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_sw_0_RREADY;

assign m_axi_gmem_sw_0_WDATA = 32'd0;

assign m_axi_gmem_sw_0_WID = 1'd0;

assign m_axi_gmem_sw_0_WLAST = 1'b0;

assign m_axi_gmem_sw_0_WSTRB = 4'd0;

assign m_axi_gmem_sw_0_WUSER = 1'd0;

assign m_axi_gmem_sw_0_WVALID = 1'b0;

assign m_axi_gmem_w_0_ARADDR = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARADDR;

assign m_axi_gmem_w_0_ARBURST = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARBURST;

assign m_axi_gmem_w_0_ARCACHE = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARCACHE;

assign m_axi_gmem_w_0_ARID = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARID;

assign m_axi_gmem_w_0_ARLEN = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARLEN;

assign m_axi_gmem_w_0_ARLOCK = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARLOCK;

assign m_axi_gmem_w_0_ARPROT = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARPROT;

assign m_axi_gmem_w_0_ARQOS = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARQOS;

assign m_axi_gmem_w_0_ARREGION = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARREGION;

assign m_axi_gmem_w_0_ARSIZE = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARSIZE;

assign m_axi_gmem_w_0_ARUSER = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARUSER;

assign m_axi_gmem_w_0_ARVALID = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_ARVALID;

assign m_axi_gmem_w_0_AWADDR = 64'd0;

assign m_axi_gmem_w_0_AWBURST = 2'd0;

assign m_axi_gmem_w_0_AWCACHE = 4'd0;

assign m_axi_gmem_w_0_AWID = 1'd0;

assign m_axi_gmem_w_0_AWLEN = 32'd0;

assign m_axi_gmem_w_0_AWLOCK = 2'd0;

assign m_axi_gmem_w_0_AWPROT = 3'd0;

assign m_axi_gmem_w_0_AWQOS = 4'd0;

assign m_axi_gmem_w_0_AWREGION = 4'd0;

assign m_axi_gmem_w_0_AWSIZE = 3'd0;

assign m_axi_gmem_w_0_AWUSER = 1'd0;

assign m_axi_gmem_w_0_AWVALID = 1'b0;

assign m_axi_gmem_w_0_BREADY = 1'b0;

assign m_axi_gmem_w_0_RREADY = p_anonymous_namespace_load_prefill_group_1_U0_m_axi_gmem_w_0_RREADY;

assign m_axi_gmem_w_0_WDATA = 128'd0;

assign m_axi_gmem_w_0_WID = 1'd0;

assign m_axi_gmem_w_0_WLAST = 1'b0;

assign m_axi_gmem_w_0_WSTRB = 16'd0;

assign m_axi_gmem_w_0_WUSER = 1'd0;

assign m_axi_gmem_w_0_WVALID = 1'b0;

assign next_scales_address0 = p_anonymous_namespace_load_prefill_group_1_U0_scales_address0;

assign next_scales_address1 = 5'd0;

assign next_scales_ce0 = p_anonymous_namespace_load_prefill_group_1_U0_scales_ce0;

assign next_scales_ce1 = 1'b0;

assign next_scales_d0 = p_anonymous_namespace_load_prefill_group_1_U0_scales_d0;

assign next_scales_d1 = 32'd0;

assign next_scales_we0 = p_anonymous_namespace_load_prefill_group_1_U0_scales_we0;

assign next_scales_we1 = 1'b0;

assign next_weights_address0 = p_anonymous_namespace_load_prefill_group_1_U0_weights_address0;

assign next_weights_address1 = 7'd0;

assign next_weights_ce0 = p_anonymous_namespace_load_prefill_group_1_U0_weights_ce0;

assign next_weights_ce1 = 1'b0;

assign next_weights_d0 = p_anonymous_namespace_load_prefill_group_1_U0_weights_d0;

assign next_weights_d1 = 128'd0;

assign next_weights_we0 = p_anonymous_namespace_load_prefill_group_1_U0_weights_we0;

assign next_weights_we1 = 1'b0;

assign p_anonymous_namespace_compute_prefill_group_U0_ap_continue = ap_sync_continue;

assign p_anonymous_namespace_compute_prefill_group_U0_ap_start = ((ap_sync_reg_p_anonymous_namespace_compute_prefill_group_U0_ap_ready ^ 1'b1) & ~ap_sync_ready & ap_start);

assign p_anonymous_namespace_load_prefill_group_1_U0_ap_continue = ap_sync_continue;

assign p_anonymous_namespace_load_prefill_group_1_U0_ap_start = ((ap_sync_reg_p_anonymous_namespace_load_prefill_group_1_U0_ap_ready ^ 1'b1) & ~ap_sync_ready & ap_start);

assign token_scales_address0 = p_anonymous_namespace_compute_prefill_group_U0_token_scales_address0;

assign token_scales_address1 = 3'd0;

assign token_scales_ce0 = p_anonymous_namespace_compute_prefill_group_U0_token_scales_ce0;

assign token_scales_ce1 = 1'b0;

assign token_scales_d0 = 32'd0;

assign token_scales_d1 = 32'd0;

assign token_scales_we0 = 1'b0;

assign token_scales_we1 = 1'b0;

assign totals_address0 = p_anonymous_namespace_compute_prefill_group_U0_totals_address0;

assign totals_address1 = p_anonymous_namespace_compute_prefill_group_U0_totals_address1;

assign totals_ce0 = p_anonymous_namespace_compute_prefill_group_U0_totals_ce0;

assign totals_ce1 = p_anonymous_namespace_compute_prefill_group_U0_totals_ce1;

assign totals_d0 = p_anonymous_namespace_compute_prefill_group_U0_totals_d0;

assign totals_d1 = 32'd0;

assign totals_we0 = p_anonymous_namespace_compute_prefill_group_U0_totals_we0;

assign totals_we1 = 1'b0;

endmodule //w4a8_linear_v1_p_anonymous_namespace_prefill_overlap
