# Re-link only the B02 XSIM objects generated by the same HDL/vector Cosim run.
[CmdletBinding()]
param([string]$MingwRoot='D:\mingw64\bin',
      [string]$VivadoRoot='D:\2026.1\2026.1\Vivado')
$ErrorActionPreference='Stop'
$root=Split-Path $PSScriptRoot -Parent
$sim=Join-Path $root 'build/b02_cache_x_hls/hls/sim/verilog'
$objectDir=Join-Path $sim 'xsim.dir/w4a8_linear_v1/obj'
$objects=@(Get-ChildItem -LiteralPath $objectDir -Filter '*.win64.obj' | Sort-Object Name)
$generated=@(Get-ChildItem -LiteralPath $objectDir -Filter 'xsim_*.c')
if($objects.Count -eq 0 -or $generated.Count -eq 0 -or $objects.Count -lt $generated.Count) {
    throw 'Incomplete generated C/object set. First run the B02 generated xelab with -mt off -v 1 and CPATH unset.'
}
$indices=@($objects | ForEach-Object {
    if($_.Name -notmatch '^xsim_(\d+)\.win64\.obj$' -or $_.Length -eq 0) { throw "Unexpected object: $($_.Name)" }
    [int]$Matches[1]
} | Sort-Object)
if($indices[0] -ne 0 -or $indices[-1] -ne $objects.Count-1) { throw 'Generated object numbering has gaps.' }
foreach($source in $generated) {
    $object=Join-Path $objectDir ($source.BaseName+'.win64.obj')
    if(!(Test-Path -LiteralPath $object) -or (Get-Item -LiteralPath $object).LastWriteTimeUtc -lt $source.LastWriteTimeUtc) {
        throw "Missing or stale object: $object"
    }
}
$savedPath=$env:PATH
$env:PATH="$MingwRoot;$env:PATH"
try {
    New-Item -ItemType Directory -Force -Path "$root/logs/b02","$root/reports/b02" | Out-Null
    $arguments=@('-Wa,-W','-O','-Wl,--stack,104857600,--image-base,0x400000','-o',
        (Join-Path $sim 'xsim.dir/w4a8_linear_v1/xsimk.exe'))+@($objects.FullName)+@("-L$VivadoRoot/lib/win64.o",'-lxv_simulator_kernel','-lxv_simbridge_kernel')
    & (Join-Path $MingwRoot 'g++.exe') @arguments 2>&1 |
        Tee-Object -FilePath "$root/logs/b02/xsim_relink.log" | Out-Host
    $code=$LASTEXITCODE
    $hashes=[ordered]@{}
    foreach($p in $objects) { $hashes[$p.Name]=(Get-FileHash -LiteralPath $p.FullName -Algorithm SHA256).Hash }
    [ordered]@{stage='B02';step='XSIM snapshot relink only';exit_code=$code;arguments=$arguments;
        object_sha256=$hashes;script_sha256=(Get-FileHash -LiteralPath $PSCommandPath -Algorithm SHA256).Hash;
        note='Relink success is not RTL verification; run the generated XSIM command and C postchecker.'} |
        ConvertTo-Json -Depth 5 | Set-Content -LiteralPath "$root/reports/b02/xsim_relink.receipt.json" -Encoding utf8
    if($code -ne 0) { throw "XSIM relink failed: $code" }
} finally { $env:PATH=$savedPath }
